services:
  - type: web
    name: crypto-price-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn crypto_tracker.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crypto_tracker.settings
